### ISSUE TITLE
Question： Is this tui support ssh ?

### ISSUE THREAD

**Issue by fastfading** [VladimirMarkelov/clui#101]
can the program run in server
is this the ui look the same in ssh client ?

**Comment by VladimirMarkelov** [comment]
I am not sure what the first question implies. As for running in ssh client, in the beginning I tried to ssh to Ubuntu using putty and run my test application - it worked. As for look the same: as far as I know , e.g, ssh client can have its own color settings (or event different number of colors comparing to original terminal) and it can use a different font that does not have some symbols used by the library by default, so it is very probable that look of the same app differs in ssh client and native terminal windows

**Comment by fastfading** [comment]
tested ,  support well in  xterm ,  mouse supported
