### ISSUE TITLE
v1.0 is not vaild semantic versioning

### ISSUE THREAD

**Issue by eu81273** [VladimirMarkelov/clui#117]
Modules are an experimental opt-in feature in Go 1.11.
But clui's latest version tag v1.0 is not valid semantic versioning so go get command couldn't fetch latest version 1.0. 
Could you retag v1.0 as v1.0.0?

**Comment by VladimirMarkelov** [comment]
Yes, I'll do it. Thanks for heads up.

**Comment by mdhorn** [comment]
I hope you will just add the new tag and not remove the existing one that others might be using.

**Comment by VladimirMarkelov** [comment]
Issued version 1.1.0 - I renamed a  control, but since the old name is still available, it is not a breaking change and I have not increased major version.

**Comment by eu81273** [comment]
@VladimirMarkelov 
It seems missing 'v'. (1.1.0 -> v1.1.0)

and I missed to say that clui is awesome :)

**Comment by VladimirMarkelov** [comment]
Good catch! Thank you. I have renamed the tag.

**Comment by VladimirMarkelov** [comment]
> and I missed to say that clui is awesome :)

Thank you a lot! :)
