### ISSUE TITLE
Кнопка растяжения окна (Window sizegrip)

### ISSUE THREAD

**Issue by prospero78** [VladimirMarkelov/clui#121]
Просьба в правом нижнем углу изменить стиль конца окна для хватания мышкой и изменения размера.

**Comment by VladimirMarkelov** [comment]
Это самый сложный из трёх ваших issues :) Потому что, я пока не представляю, как тут получше UX сделать - вариантов немного в голову приходит. Есть какие-нибудь конкретные предложения?

Цветом выделять - не вариант, у нас их вего 16. Пестро будет или ужасно. Выделять только у активного окна другими симолами? Кроме такого мне ничего в голову не пришло:

```
1╔Demo═══════[^↓X]╗
 ║                ║
 ║                ║
 ║                │
 ╚═══════════════─┘
```

Еще вариант - чуть расширить границу захвата, включив дополнительный символ, что в углу, а не только сам угол. Но это тоже не ясно, имеет ли вообще смысл

**Comment by prospero78** [comment]
Есть в utf-8 специальная литера -- залитый фон
[https://unicode-table.com/ru/#box-drawing](url). их там тонны, вот такие и предлагаю.

**Comment by VladimirMarkelov** [comment]
Это был комментарий на этот тикет или про `X`? :) Потому как boxes сюда не очень подзодят или я не понимаю, что имеется в виду

**Comment by prospero78** [comment]
Да все мои иссуси можно позакрывать. Так, благие пожелания. Форкнул и активно кромсаю!))

**Comment by VladimirMarkelov** [comment]
Остальные 2 иссуся закрывать не буду :) Отделить закрыть от развернуть+свернуть - идея интересная. Не зря же борланд так сделал тоже. Я просто мало мышкой тыкал, чтобы прочувствовать проблему. А этот тикет повисит пока. Если идей не будет, как это сделать, чтобы было прилично выглядящим, то и закроем.
