### ISSUE TITLE
Кнопка управлением окна (Replace window close icon 'O' with 'X')

### ISSUE THREAD

**Issue by prospero78** [VladimirMarkelov/clui#122]
Просьба заменить кнопку управления состоянием окна в верхнем правом углу "О" на "Х" -- вводит в заблуждение. Также будет полезным подсветить фон кнопок (можно даже разными цветами).
А так -- вери найс Турбо Вижно для голанга))
🆘

**Comment by VladimirMarkelov** [comment]
Спасибо на добром слове :)

Я уж и не помню, почему я выбрал 'O'. Может быть, искал что-то похожее на турбо-вижиновский квадрат. В целом, согласен - можно будет заменить O на X по умолчанию.

**Comment by VladimirMarkelov** [comment]
Можно ещё попробовать `■` - похож на турбовижн. А fallback в ASCII теме можно и `X` сделать.

**Comment by prospero78** [comment]
Да, Это уже вариации. Но тоже годно.
