### ISSUE TITLE
Кнопки управления: расстояние (Window icons: extra spacing between icons)

### ISSUE THREAD

**Issue by prospero78** [VladimirMarkelov/clui#123]
Прошу добавить, хотя бы один пробел между кнопками управления окном. Так будет легче тыкать мышкой.

**Comment by VladimirMarkelov** [comment]
Это уже из области субъективных ощущений :) Поэтому один вариант, чтобы продошёл всем сделать крайне сложно. Я предпочитаю компактность. Но я и мышкой почти не пользуюсь в консоли(самый частый случай: закрыть приложение, но и тут в большинстве случаев CtrlQ CtrlQ и готово).  Так же хотелось бы обойтись минмумом дополнительных новых настроек, чтобы старые исходники не пришлось много переделывать. Как вариант, чтоб не испортить совместимость, можно добавить в тему опцию типа "ExtraButtonSpace=true/false" и от неё плясать уже. Ну и надо выбрать лучшние варианты CompactButtons & SpacedButtons. С CompactButtons-то понятно - это текущая. А вот с пробелам я навскидку сразу 5 штук придумал, разной степени ужасности (можно предложить еще свои варианты). В список я включил и текущий:

```
1╔Demo═══════[^↓X]╗   // current
 ║                ║
 ║                ║
 ║                ║
 ╚════════════════╝
2╔Demo═══[ ^ ↓ X ]╗  // one space between icons and icon group borders
 ║                ║
 ║                ║
 ║                ║
 ╚════════════════╝
3╔Demo═════[^ ↓ X]╗  // one space only between icons
 ║                ║
 ║                ║
 ║                ║
 ╚════════════════╝
4╔Demo═══[^  ↓  X]╗  // two spaces between icons
 ║                ║
 ║                ║
 ║                ║
 ╚════════════════╝
5╔Demo═══[═^═↓═X═]╗   // one filled space between icons
 ║                ║
 ║                ║
 ║                ║
 ╚════════════════╝
6╔Demo════[^^↓↓XX]╗   // icons are doubled for easier cliking
 ║                ║
 ║                ║
 ║                ║
 ╚════════════════╝
```

**Comment by prospero78** [comment]
Вместо стрелки вниз (имхо) -- лучше использовать знак "_", и располагать его слева от развернуть. Я вообще предпочитаю эти два знака выносить влево, а закрыть оставляю справа -- промах по "Х" -- критичен бывает.

**Comment by VladimirMarkelov** [comment]
> предпочитаю эти два знака выносить влево

это даже как-то больше в духе Turbo Vision. Сегодня пересматривал скриншоты и увидел, что у них закрыть и развернуть с разных сторон. Неплохой вариант, надо попробовать. Тогда и пробелы ставить уже не обязательно, если я правильно понимаю.

**Comment by prospero78** [comment]
Точно.
