### ISSUE TITLE
Unable to edit table 

### ISSUE THREAD

**Issue by MostHated** [VladimirMarkelov/clui#126]
Heya,  
I was working on trying to add a new arbitrary popup type that I could add a table in it's own window but upon messing around with the table itself, I can't see to get the editing functionality to work. I went into the tables in the demo files and they were unable to be edited that I could see either (pressing F2 or Enter), am I missing a step or is this functionality not implemented/bugged? In the demo, if you try to edit, it opens a dialog that simply says to press the button or hit space to close it.

Thanks,
-MH

**Comment by VladimirMarkelov** [comment]
Hi!

I've updated `demos\tableview\tableview.go` - now it shows how to use a basic dialog to edit a value in the table.

**Comment by MostHated** [comment]
Fantastic, thank you very much! : D
