### ISSUE TITLE
Display formatted text?

### ISSUE THREAD

**Issue by MostHated** [VladimirMarkelov/clui#129]
Heya,  
Is it possible to display preformatted text? I realize displaying something like markdown format would probably be a bit much, but at least being able to have leading tab/spaces or similar? I tried to have a textview load from a file which had some text that had some spaces and tabs and such but it just disregarded them and all text started at 0 of the line.

Thanks,
-MH

**Comment by VladimirMarkelov** [comment]
I thought it should preserve leading spaces. I'll check this out.

**Comment by MostHated** [comment]
I got it figured out actually just a little bit ago. I simply changed this.

```Go
	scanner := bufio.NewScanner(input)
	for scanner.Scan() {
		line := scanner.Text()
		// line = strings.TrimSpace(line)
		l.lines = append(l.lines, line)

	}
```
It no longer did it anymore once I did that. I was using it as a log viewer, so I want to try and retain as much of the original as I can. It is looking much  better now.

**Comment by VladimirMarkelov** [comment]
Is it a patch for a source inside the library? In this case, I think I should change `TrimSpace` to `TrimRight` - sometimes I had a text with a lot of spaces at the end of line. I think removing trailing spaces does not harm anything. I'll fix it

**Comment by MostHated** [comment]
Yeah, it was in the textview.go under the function LoadFile.
