### ISSUE TITLE
Change bg color after selection[TableView]

### ISSUE THREAD

**Issue by noroot777** [VladimirMarkelov/clui#142]
Hi
How can I change the bg color after cell selection?
For example, I change the bg color of the cells in the selection row, to mark this row was read.

**Comment by VladimirMarkelov** [comment]
Hi,

As far as understand, you want to have different background color for "visited" cells. Correct?

In this case, I think, the current solution is like this:

1. Create an array somewhere that will hold visited cells
2. On cell select event add the cell to the vector
3. Override `OnDrawCell` event, and inside it check if a cell with corrdinates `event.Row` and `event.Col` is "visited". If so, change event's value `event.Bg` to your custom one. To avoid hiding highlight for the current selection, additionally you can check `event.RowSelected` and `event.ColSelected` - if both are `true` - do not apply your `Bg`, let it paint with default one.

**Comment by noroot777** [comment]
It seems works. Thanks.
But there's another issue that I mind just now. `SetFullRowSelect` not works.
I set this in my code `tabEvents.SetFullRowSelect(true)`, but only the selected cell hiliting, not the whole row.
Am I missing something?

**Comment by noroot777** [comment]
The whole row of NO.11 should be hiliting as my consider, but only the selected cell.

![image](https://user-images.githubusercontent.com/1926268/101136599-8c0adf00-3648-11eb-8015-43fa9d89a956.png)

**Comment by VladimirMarkelov** [comment]
Is it with default draw handler? Or you have overloaded it?

**Comment by noroot777** [comment]
Sorry, my fault, I changed the TableSelectedText attr in theme file. For my theme above, when I set `TableSelectedText=white bold`, it will hiliting the whole row.

![image](https://user-images.githubusercontent.com/1926268/101229828-14d35a80-36dd-11eb-8f3b-8a3003eeb3df.png)
