### ISSUE TITLE
view.OnKeyDown ?

### ISSUE THREAD

**Issue by gerey73** [VladimirMarkelov/clui#148]
Поскольку Вы видимо соотечественнки, а я слаб в английской мове :) , то разрешите уж на "великом и могучем" задать Вам вопрос!?
Я собственно неофит в Go  и пока не очень понял прелести interface, но сумел состряпать небольшое приложение, но хочеться использовать "шоткаты" и видимо надо пользовать OnKeyDown.
Я просто не очень понял значения параметров для данного колбэка и хотел попросить Вас привести небольшой пример! ;)
Спасибо!

**Comment by VladimirMarkelov** [comment]
Глобальных горячих клавиш не предусмотрено. Можно попробовать задать OnKeyDown для конкретного Window. Наверное, при одном окне будет как глобальное. Часть контролов определяют вдобавок OnKeyPress - тут кроме кода клавиши/комбинации ещё приходит печатный символ. Полезно для Edit/ListBox/Table, чтобы фильтровать нажатое пользователем. В целом, OnKeyDown получает системный код клавиши или комбинации клавиши: и нажатие на букву и нажатие буква+Ctrl каждое сгенерирует свой собственный уникальный код. По нему не выйдет однозначно получить букву(скажем, и для латиницы и для кирилицы код придёт один, но буквы-то должны печататься разные). Именно поэтому, контролы, которые нуждаются в конкретной нажатой букве реализуют ещё и OnKeyPress. Какие комбинации клавиш поддерживаются(а поддерживаются не все варианты комбинаций), можно глянуть в библиотеке `nsf/termbox-go`, в файле `api_common.go`.

Конкретно для OnKeyDown примеров вроде нет. Но работа с ним практически ничем не отличается от OnKeyPress. А для OnKeyPress есть неколько примеров. Первый: в главном демо `maindemo` для поля ввода обрабатывается нажатие на Enter, чтобы изменить положение ProgressBar и обновить выбранный элемент в выпадающем списке. Так же, можно глянуть `fileselectdlg.go`: там несколько разных обработчиков реализовано.
