### ISSUE TITLE
EditField and Slash

### ISSUE THREAD

**Issue by F-r-o-i-d** [VladimirMarkelov/clui#151]
when you enter a "\\" on a EditField it delete last charactere
![image](https://user-images.githubusercontent.com/82611242/174266039-ba0ec860-7c40-462e-8671-6e0129b12bc9.png)
## when i press "\\"
![image](https://user-images.githubusercontent.com/82611242/174266062-2ea5b246-364b-4ba9-abd2-c5ee1effd8c3.png)

**Comment by VladimirMarkelov** [comment]
I wonder if it depends on a terminal emulator. I use Windows Terminal 1.13. Neither of slashes deletes the last letter. Here is a screen cast:

![slashes](https://user-images.githubusercontent.com/1577186/174408338-b1c75e61-7011-48c9-bc26-cf61811f08b4.gif)

**Comment by F-r-o-i-d** [comment]
maybe finaly i have use a fileselect
