### ISSUE TITLE
Cross platform?

### ISSUE THREAD

**Issue by lostinblue** [VladimirMarkelov/clui#52]

**Comment by VladimirMarkelov** [comment]
Sorry, it took a long time to reply. Frm the beginning I wanted to create crossplatform library. That is why I stopped developing a termbox branch with full-mouse support.  In the beginning demos worked good on Windows and Ubuntu. I need to check the latest code and fix if it does not work.

**Comment by VladimirMarkelov** [comment]
Yes, it has some trouble in Ubuntu. Will fix it.

**Comment by VladimirMarkelov** [comment]
What are the 'troubles'? Could you elaborate it?
I cloned the project to Ubuntu16 server to fresh directory. Then I ran maindemo and saw no issues.
