### ISSUE TITLE
Console apps

### ISSUE THREAD

**Issue by carlca** [VladimirMarkelov/clui#54]
Hello Vladimir. This is a really impressive package with some nice looking demos. One small issue, the demos work in Windows under ```cmd``` but not under any of the Bash style consoles such as Msys2 or Git Bash. SInce I spend most of my days typing ls and cd /go and such like it would be good to use these console apps. It's not a huge issue, and I'll understand if it's not possible, just curious really.

**Comment by VladimirMarkelov** [comment]
Hello,
Thank you :)
I have never tried my apps inside Msys2 or Git bash. I'll try and see what is going.

**Comment by VladimirMarkelov** [comment]
Could you write more detail about the issue? I just tried clui_demo, barchart and tableview in GitBash and all of apps works as expected, except a small issue with text cursor after a window is resized - not included in demo that I've recorded(Please see CLUI demo working in GitBash on Windows7 64-bit here: [GitBash Demo](https://github.com/VladimirMarkelov/clui/blob/master/demos/gitbash01.gif)).

**Comment by carlca** [comment]
Strange. I'm running under Windows 10 Pro. Maybe that's the difference. It definitely does not work with Git Bash here.

**Comment by carlca** [comment]
Hi Vladimir, where did you download your Git Bash. Your version appears to be 3.1.0 whereas mine is 4.3.46(2) - maybe it's a version difference.

**Comment by VladimirMarkelov** [comment]
I installed Git from official web-site(git-scm.com) a long time ago and never updated it - it does its job well :) If I am not mistaken it was Git version 1.9.x.

I've tried MSYS2 with 4.3.36(2) and now I see that it does not work - it is just stuck and shows nothing. It is interesting

**Comment by VladimirMarkelov** [comment]
I found the following issue: https://github.com/jroimartin/gocui/issues/64
It seems the trouble is common

**Comment by carlca** [comment]
Thanks for looking Vladimir. I'll try to grab a copy of that Bash Git.

**Comment by carlca** [comment]
Yay! I was able to downgrade to Git 1.9.5 and it seems that the copy of Git Bash included with it is sufficiently primitive to work. Thanks a lot for all your help. Now to start writing some console apps!
