### ISSUE TITLE
Please tag releases with git tags

### ISSUE THREAD

**Issue by skovtunenko** [VladimirMarkelov/clui#59]
Hello! Thanks for a great tui library!
Having changelist is great, but can you tag your code with git tags also ?
Thanks!

**Comment by VladimirMarkelov** [comment]
Thank for using my library! That's very inspiring to know that people use what I have done initially for myself but then decided to share with everyone.

A good idea. I'll do it next time when I increase minor or major version. The last times I changed build numbers it was only one commit for every build change(except cases when README was changed), so it did not look good to have a git tag for every commit.

**Comment by VladimirMarkelov** [comment]
P.S. I'm glad you liked the library ;)

**Comment by skovtunenko** [comment]
> so it did not look good to have a git tag for every commit.

Yes, you are right. Only breaking changes required new version tag.
Nowadays, dependency management tools (like `dep`) can use tag name to fetch specific version of the lib.
