### ISSUE TITLE
race conditions

### ISSUE THREAD

**Issue by cassandraMetro** [VladimirMarkelov/clui#60]
Hi,
running go build -race on all demo programs shows several data races. I am not sure if it is a problem in the lib or in the demo apps. I had some not explainable index out of bounds errors in my own program so I started searching with -race.

**Comment by VladimirMarkelov** [comment]
Thank you for the report. Good catch. My apps were fairly simple, so I did not get any trouble. Anyway the library can have hidden issues.

**Comment by VladimirMarkelov** [comment]
The first step is done: demos and termfb2 (all are executed with -race option) do not generate any warning after some usage. But I now there are more places to fix

**Comment by cassandraMetro** [comment]
Great Work!! Demos working now.

**Comment by cassandraMetro** [comment]
Sorry for accidentally closing this !
