### ISSUE TITLE
would u like to convert it to css?

### ISSUE THREAD

**Issue by hookmethods** [VladimirMarkelov/clui#62]

**Comment by VladimirMarkelov** [comment]
Could you elaborate it, please? What would you change and how?
I agree, my way is not standard. If it can be improved it worth trying. 
In the beginning when there was no theming and I used the solution that does not require much work or external dependencies to just make label multicolored. I thought that using css way was a huge overhead for just text and background colors.

**Comment by hookmethods** [comment]
I currently working on a terminal system for the web as a project of my studio, I personally really like the classic layout, UI's. so I may will not do the smart design, just want to keep it simple, clean.

this terminal system can be access to your bios, os installation and much more just like a saas system

**Comment by VladimirMarkelov** [comment]
OK, I see. But something is still unclear. How are you going to use my library for your project?

**Comment by hookmethods** [comment]
pay is indeed if u can help us to convert

**Comment by VladimirMarkelov** [comment]
In other words, it was not an issue about the original library. It was a question about doing something for some web stuff that looks like the library. I am not sure what it requires to do. Anyway, I am sorry, I am no web developer and I hardly can help you to port the library to something web-based.
Moreover, it is not clear what is terminal in your case. if you have no terminal of your own, you have to create something like termbox library on which my library depends on.
