### ISSUE TITLE
scrollbar doesn't work at all

### ISSUE THREAD

**Issue by pjebs** [VladimirMarkelov/clui#70]
Tableview demo: The scrollbars don't work at all. In fact I have no idea how to even use it.

It seems to work when I first run it.
When I stop interacting with the horizontal scrollbar and then use the vertical scrollbar and try and use the H-scrollbar, it no longer responds to mouse.

This is also the case when I enlarge the window, the scrollbars stop responding to mouse afterwards.

**Comment by VladimirMarkelov** [comment]
Unresponsive scrollbars are fixed.

Dragging scrollbars looks very ugly and I am not sure it works as expected. Now scrollbars is better to use as extra PgUp/PgDn(when you click empty space on a vertical scrollbar) and Left/Right keys(clicking empty space on horizontal scrollbar). The right-bottom character of the TableView (bottom right corner between two scrollbars) is used to move to the latest row/column using mouse, like Alt+End combination. Arrows on scrollbars moves current as expected but in the current implementation horizontal scrollbar arrows duplicates clicking empty space on the horizontal scrollbar.

**Comment by pjebs** [comment]
i think it works well enough.
