### ISSUE TITLE
AlertBox

### ISSUE THREAD

**Issue by pjebs** [VladimirMarkelov/clui#76]
I think another good Dialog is a simple alert box that simply displays a message modally and has 1 button.

eg. "Password incorrect. Please try again."
or "Could not connect to internet."

This is similar to javascripts: `alert()`: https://www.w3schools.com/js/js_popup.asp

**Comment by pjebs** [comment]
Actually a better way is just make a convenience function that is a special case of `ConfirmationDialog` but automatically configured with 1 button.

**Comment by pjebs** [comment]
The dialogs show provide a way for us to select if they can be moved by mouse using the new commit.
Also they should not have the buttons on the top-right.

Perhaps expose `View` in the dialog so we can make the changes ourself.

**Comment by pjebs** [comment]
See: https://github.com/VladimirMarkelov/clui/pull/77

**Comment by VladimirMarkelov** [comment]
Before exposing View, I think, it is good to fix issue #78. Otherwise work with exposed View can be dangerous. Let's merge it later.

**Comment by VladimirMarkelov** [comment]
Why do you need access to internal View to create custom alert dialog?
Now you can do: 
```go
    dialog := CreateConfirmationDialog("Job completed", "Job #10 completed", ui.ButtonsOK, ui.ButtonDefault)
```
A new function saves only one argument and does not allow a user to set custom title for the button.

**Comment by pjebs** [comment]
Internal view mostly to access new functions to stop user moving it and hiding top right controls.

**Comment by VladimirMarkelov** [comment]
I see. Let's merge your patch
