### ISSUE TITLE
Bug report

### ISSUE THREAD

**Issue by pjebs** [VladimirMarkelov/clui#78]
No idea what is going on.
I have a listbox with some values.
When I click on the listbox, I have a modal confirmation box popup with a display of the selected value.

**Comment by pjebs** [comment]
![bug report - 1](https://user-images.githubusercontent.com/5377970/35323236-f597c0ae-0140-11e8-9413-3d6c6650e320.gif)

**Comment by VladimirMarkelov** [comment]
I think I know what is the trouble. I had similar troubles when I tried to create Windows inside control handlers. I have to do some architectural changes to make critical places that work with Windows thread safe.

**Comment by pjebs** [comment]
I can send you my code if you want

**Comment by pjebs** [comment]
I think it has now been fixed. There is a small glitch grey character cursor (caret) that is near the middle of the screen.
