### ISSUE TITLE
Detect when terminal size changes

### ISSUE THREAD

**Issue by pjebs** [VladimirMarkelov/clui#79]
I want to always have my listbox window in the middle of terminal screen.

How can I detect when terminal size changes.

I can see at the bottom of:
```
type Event struct {
    // Event type - the first events are mapped to termbox Event and then a few
    // own events added to the end
    Type EventType
...
    // For resize event - new terminal size
    Width  int
    Height int
}
```

**Comment by VladimirMarkelov** [comment]
Yes, the event is caught by the library but is not propagated further. I can add a size-change handler for Window control.

**Comment by pjebs** [comment]
that would be good
