### ISSUE TITLE
Delve doesn't attach

### ISSUE THREAD

**Issue by pjebs** [VladimirMarkelov/clui#80]
For some reason, Delve debugger doesn't attach to programs that use this package (or maybe termbox)

```
gdlv run *.go (gdlv is just a graphical front-end for delve)

OUTPUT error:
runtime.main_main·f: relocation target main.main not defined
runtime.main_main·f: undefined: "main.main"

exit status 2
```

**Comment by VladimirMarkelov** [comment]
maybe it is the issue:
https://stackoverflow.com/questions/14739188/how-to-fix-this-error-runtime-main-undefined-main-init
?

If you run *.go it runs *_test.go files as well. Try to delete all *_test.go files and then execute delve.
