### ISSUE TITLE
Panics

### ISSUE THREAD

**Issue by pjebs** [VladimirMarkelov/clui#81]
Sometimes when I panic with some long detailed information passed to panic function, it works perfectly as intended.

The App crashes, the long text is printed with stack trace and you can continue typing things in the terminal (including rerunning the program).

Other times, the terminal is unresponsive after the panic and as such you can only see the bottom of the long detailed information. The terminal doesn't scroll up to see the rest of the information.

I can type information in the terminal but I can't see the text being written. However it actually is being written because if I type `go run *.go` the program will start up again.

**Comment by pjebs** [comment]
![screen shot 2018-01-26 at 6 26 44 pm](https://user-images.githubusercontent.com/5377970/35429073-860da44c-02c6-11e8-95a6-a5f606e06d4b.png)

**Comment by pjebs** [comment]
You can see in the image. That is after I panic deliberately with a long detailed multi-line text string.
I can't scroll up to see the top of the test string. Also the keyboard doesn't response so it doesn't show what I am typing - even though the keyboard is actually working because I can type stuff and the command still works such as `go run *.go` will restart the program.

**Comment by pjebs** [comment]
I found a fix to the problem:
When I deliberately want to `panic`, I now call `defer ui.DeinitLibrary()` on the line before.
That solves the problem.

**Comment by pjebs** [comment]
I was thinking about the solution above and why sometimes when I paniced it froze up terminal and other times it didn't.

```
func mainLoop() {
	// Every application must create a single Composer and
	// call its intialize method
	ui.InitLibrary()
	defer ui.DeinitLibrary() . /// <------If I panic, this *should* always be called eventually

	ui.SetThemePath("themes")

	createEventsWindow()

	// start event processing loop - the main core of the library
	ui.MainLoop()
}

func main() {
	mainLoop()
}

```

**Comment by pjebs** [comment]
```
func createEventsWindow() {

	mainWindow := ui.AddWindow(0, 0, 20, 7, "Event Organizer")
	mainWindow.SetMaximized(true)

	W, H := mainWindow.Size()

	//Create dialog for logging inside
	createLoginWindow(W, H)

	//Create listview for upcoming events
	eventsList = ui.CreateListBox(mainWindow, 20, 20, ui.Fixed)



	eventsList.OnSelectItem(eventSelected) //Is callback being called on a separate goroutine?

}

// eventSelected will be called when an event is selected from the list
func eventSelected(ev ui.Event) {

	ui.CreateAlertDialog("Event selected", eventsList.SelectedItemText(), "OK")

	details, err := fetchEventDetails(eventsID[eventsList.SelectedItem()])
	if err != nil {
		panic(spew.Sdump(err))
	}
	defer ui.DeinitLibrary() //I need this line here to prevent terminal from freezing.
	panic(spew.Sdump(details)) //I am panicing here.
}
```

Does that mean that `eventsList.OnSelectItem(eventSelected)` is being called in a `separate goroutine`?

**Comment by pjebs** [comment]
I am an iOS developer. I know it is the same for Android development too.
The #1 rule in ios development (this gets emphasised from day 1 when you learn) is that you can do things in different threads, that is fine **BUT** if you are doing **ANYTHING** related to the `UI`, it must be done in the `mainthread`. Apple provides easy convenience functions to access and execute code in the main thread.

I think you you may need to consider forcing such a principle.

**Comment by pjebs** [comment]
That way, you call all the callbacks without executing in a goroutine, and if the user of the library wants to use a goroutine, then we can do so inside our own event handler callback.

**Comment by pjebs** [comment]
https://github.com/golang/go/wiki/LockOSThread
https://github.com/faiface/mainthread
https://github.com/olahol/mainthread

**Comment by VladimirMarkelov** [comment]
It is rule for all OSes, I think. Even if it is possible to work with UI from a few threads, it is not recommended. Most of events are generated now in main thread. But few events still create a new thread on firing.

We can try to make all events run inside main thread - if a user wants to do a heavy job, the user can run his/her own thread - and see what happens. My apps were mostly one-dialog ones, so I have not spotted any issues.

**Comment by VladimirMarkelov** [comment]
Duplicates #82
