### ISSUE TITLE
Anyway to display images

### ISSUE THREAD

**Issue by pjebs** [VladimirMarkelov/clui#83]
Is there anyway to draw images (png/jpeg) in CLI program without using image->ASCII art converter?

**Comment by pjebs** [comment]
Like here:
https://unix.stackexchange.com/questions/35333/what-is-the-fastest-way-to-view-images-from-the-terminal

**Comment by pjebs** [comment]
https://github.com/stefanhaustein/TerminalImageViewer
https://github.com/substack/picture-tube

**Comment by pjebs** [comment]
Go example: https://github.com/olivere/iterm2-imagetools (but i think only for macos)

**Comment by pjebs** [comment]
Another go example: https://github.com/eliukblau/pixterm (should work for all os)

**Comment by VladimirMarkelov** [comment]
I do not think this feature should be a built-in one in terminal UI library. Firstly, it requires a lot of work to support different types of terminals. Secondly, it requires to add a few dependencies like png, jpg etc to a library to use once in a while.

As for 'should work for all OSes'. All examples above (except nodejs one that sticks to terminal of 256 colors) require either iTerm(that is OSX only solution) or True-Color mode(that is not always available: e.g, Linux without a DE - raw terminal - it is 16 color one or worse (at least on my test Ubuntu server it is 16 color one), Windows terminal is limited to 16 colors as well. In other words, it must be a set of methods to convert an image to any possible terminal. And it is the whole story. Two more notes:
1. As far as I see, termbox does not support True-Color. 
2. If a terminal uses indexed colors than its colors may be very different from what you want to show. Example: I use 16 color terminal with solarized color scheme - it does not have green color at all. How to show pictures with correct colors in this case?
