### ISSUE TITLE
Paste content is truncated

### ISSUE THREAD

**Issue by soyking** [VladimirMarkelov/clui#94]
Here is my test code for EditField:

```
package main

import (
	ui "github.com/VladimirMarkelov/clui"
)

func mainLoop() {
	ui.InitLibrary()
	defer ui.DeinitLibrary()

	view := ui.AddWindow(0, 0, 0, 0, "")
	view.SetMaximized(true)
	ui.CreateEditField(view, 200, "", ui.Fixed)

	ui.MainLoop()
}

func main() {
	mainLoop()
}
```

I ran it on macosx and when I pasted `test`, it just showed `t` in the EditField. Could it be fixed? Thanks.

**Comment by VladimirMarkelov** [comment]
How do you paste text? As I see Ctrl+V is disabled for macos and there is no clipboard call in edit_osx.go.

**Comment by soyking** [comment]
emmmm… I used command + V in iTerm2. And I found that the order is mess too.

**Comment by VladimirMarkelov** [comment]
So, it pastes using system functions. Unfortunately I do not have any macos laptop and I cannot debug.

What happens if you try to use library clipboard support? E.g, copy 
```go
case term.KeyCtrlV:
	if !e.readonly {
	s, _ := clipboard.ReadAll()
		e.SetTitle(s)
		e.end()
	}
return true
```
from edit_other.go to edit_osx.go? To make experiment clearer you can replace hotkey `KeyCtrlV` with any other unused one.

**Comment by soyking** [comment]
Yeah it works. Though it is a little werid to use ctrl but not command in mac.

But I want to run it on Linux, so it is fine. Thanks.
