### ISSUE TITLE
Shift+Tab does not work

### ISSUE THREAD

**Issue by ilius** [VladimirMarkelov/clui#95]
Shift+Tab should switch the focus to the previous widget.
I did a little debugging in `Window.ProcessEvent`, looks like Shift+Tab is recognized as 3 events instead of one.

```
2018/06/13 13:57:47 Key=1B, Mod=0, Type=0
2018/06/13 13:57:47 Key=0, Mod=0, Type=0
2018/06/13 13:57:47 Key=0, Mod=0, Type=0
```

EDIT: Looks like this is a bug in [termbox-go](https://github.com/nsf/termbox-go/issues/148)
I'm also surprised there is no `KeyShift` in termbox

**Comment by VladimirMarkelov** [comment]
yes, I wanted to have both Tab and Shift+Tab initially but did not find it in termbox.  That was why Shift+Tab did not implemented.

I have not checked yet 'https://github.com/gdamore/tcell' - if it supports Shift+Tab. As I understand termbox repo is frozen and won't be developing any longer. tcell has a module that simplifies moving to tcell from termbox. It needs testing.

**Comment by ilius** [comment]
Oh, I didn't know termbox is discontinued
I took a glance at `tcell`'s code, looks much better in terms of design, at least it has binary mask for key modifiers (called `ModMask`), same as Gtk, so it can support shortcuts with multiple modifiers! (unlike termbox which is poorly designed)

**Comment by VladimirMarkelov** [comment]
I was sure that I read about it somewhere. But I failed to find any proof. At least termbox-go is still kind of alive - I see some PRs merged recently. So, I may be wrong.

**Comment by ilius** [comment]
I think tcell is a better library regardless. But looks like migrating to requires a huge refactoring.
For example the theme and colors (being Bold is part of `tcell.Style`, not `tcell.Color`)

Have you also seen [tview](https://github.com/rivo/tview)? That's also using MIT license so we can interchange codes. And Shift+Tab works in examples.

**Comment by VladimirMarkelov** [comment]
I'm sorry for the late reply, Thank you a lot for the link. When I looked for a TUI library I did not find anything like tview. It looks really great. I have not check what it can do, but I already see some things my library does not have
