### ISSUE TITLE
Feature request - file picker

### ISSUE THREAD

**Issue by mbolder** [VladimirMarkelov/clui#98]
A great additional widget would be a file picker. 

* [x] file picker
* [x] demo
* [x] update docs
* [x] update changelog

**Comment by VladimirMarkelov** [comment]
I thought about it. It is not an easy task but doable

**Comment by mbolder** [comment]
That would be brilliant. In the meantime, can you think of any other quick solution to select a file in a golang app in the terminal?

**Comment by VladimirMarkelov** [comment]
@mbolder I am sorry for the delay. These days I have little time for my hobby projects. I cannot make up a quick solution at this moment. But, there is a good news as well: work on a basic file picker is close to be completed. I hope I finish it by the end of this week. I found a few issues with controls, so the final patch will include:

- File picker (file/directory save/load dialog) - yet, no multi-selection, it is not easy to implement using the existing controls
- Fix for ListBox about correct event firing
- new method for ListBox. It maybe not very useful in general but for file list it may be good to have
- A new property of Label
- A demo for the file save/load dialog

**Comment by mbolder** [comment]
That's brilliant thank you very much for the fast reply. One last question. Would it be possible to create an example, where a "fileSelect" function is called, which returns the selected file path/name as a string , with a simple window like in the example that pops up on select. Given the options to select a file or cancel. After which the select window closes.

**Comment by VladimirMarkelov** [comment]
Since dialogs (even modal ones) work asynchronous, there is no simple example. I cannot write a good example off the top of my head at this moment. But I think it requires to create a function waiting on a channel, and the value is put to channel inside dialog onClose. Something like this (the code is untested and may not work - just to show the idea):
```go
ch := make(chan string)
dlg.OnClose(func() {
  if !dlg.Selected {
     ch <- "" // or you can just close(ch), so you get an empty string as well
     return
  }
  ch <- dlg.FilePath
}
selectedFile <- ch
```
